### ISSUE TITLE
程序出现错误

### ISSUE THREAD

**Issue by mthli** [dengshuan/cmcc-edu#1]
# python2 cmcc_edu.py login

正在登录...
Traceback (most recent call last):
  File "cmcc_edu.py", line 46, in <module>
    'wlanacssid':wlanacssid
NameError: name 'wlanacssid' is not defined

**Comment by dengshuan** [comment]
CMCC-EDU将 redirect url 中的 _wlanacssid_ 换成了_ssid_ ，以前准备实现CMCC和CMCC-EDU都能登录的客户端，所以直接从URL中读取_ssid_，现在直接将 _wlanacssid_ 设为 CMCC-EDU 就可以解决问题了
